### PR TITLE
add amonkhet remastered

### PR DESCRIPTION
**Pull request by jcencek**

### CODE REVIEW

**Comment by jjallaire** [comment]
Thank you for this! We do need ratings though for the drafts to be acceptably realistic. I hadn't yet gotten around to deriving ratings script for AKR (it involves scraping from https://apps.draftaholicsanonymous.com/). Let me take a shot at that later today or tomorrow. I'll amend your PR w/ the ratings once I have them.

**Comment by jjallaire** [comment]
Thanks, just merged along with ratings. Should be deployed shortly. LMK if you have any issues.

**Comment by jcencek** [comment]
Thanks so much!

I do notice the split card images from AKR aren't readable due to their lack of oracle text (which is why I opted to use the non-digital images initially), e.g.:
https://c1.scryfall.com/file/scryfall-cards/large/front/6/c/6ca9225f-9b9f-49d0-b92b-d23e3d49fb37.jpg?1597251353

I don't have a strong preference since I'm familiar with the cards, but just wanted to point out. Either way, thanks so much, will try this out right away!!

**Comment by jjallaire** [comment]
@jcencek Thanks for pointing that out, I missed that note in your original PR. I've just deployed an update that uses the paper images for those cards (the CI service I use to build and deploy is down right now though so you won't see the update until they get back online)

**Comment by jjallaire** [comment]
Okay, should be live now w/ the correct images.

**Comment by jcencek** [comment]
Thanks!

**Pull request merged**
